language: python
python: 3.6
branches:
  only:
  - master
  - nightly
  - ci
  - "/^(release\\/)?v([1-9]\\d*!)?(0|[1-9]\\d*)(\\.(0|[1-9]\\d*))*((a|b|rc)(0|[1-9]\\d*))?(\\.post(0|[1-9]\\d*))?(\\.dev(0|[1-9]\\d*))?$/"
before_install:
- pip install -U pip setuptools wheel
- pip install -r requirements-ci.txt
install: pip install -e .
script: py.test -v --cov=yhttp
after_success: coveralls
after_deploy: ./.travis-upload-doc.sh
deploy:
  provider: pypi
  skip_cleanup: true
  user: Vahid.Mardani
  password:
    secure: RjldAKbHt/IVf1RoWu4WAe5Z5nd2T6BMJoz0PMM8rl9a988GO7jUa5Xjy/6bj4oOJpGysDeNEPXxkaf1S6OZ4xDq3pH8GU2N0VWwurlE3ZiIHNr1qL74iYyMf9ilWnWakZ5oLZRfRawH+3ibI2VhbuwjmMHc9EiSXZ9yqN0Pbg9c05HrKmwPPwywAKFqFy9bqxNfdYNUVrW1bOSrjzhhiTW7Wwx5slBHdxei35zfmhqi+wUouWc3M8pH47f9eQFD5Ao1e5knLBJdO69IVeAlmIAzrOgOtGEnNS3OMw9tDQbZXscgpMERc65zSN27DOsRQJnQor+qA0etb7dNE7BZou/dJ2wcdINIjfhC94mZTJAVFs76ruWiEyGvZaMq5n/kBrautugdnBlRQtUiPvt2x31w4jtX1m5qxJkdY+b2XEwdr71zgI0ux8BysWHyWNZDRkbeHcgcAdg/0dTtj0C1GhNzYqXC62mntaV1NBmyudy38B4QI0TFqyWdRP3BX4U0ZFT7K38D3GsnhQANdVGWme1Vz266Odz3XbCNHbh8Cad3F1nPyBHdzq3iPNq3B31m1F3kI6UcwMYQOKgEgujJwAdg9pghq0Orv3wcHFdATYV18N8ubjscrwFDbC34Sz1PeA5ToBTOzz+wtm3+DgF3EXJMYLZ+G6FKVNVHVaVBg8k=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: yhttp/yhttp
    condition: "$TRAVIS_PYTHON_VERSION = 3.6"
