name: Documentation

on:
  release:
    types: [created]

jobs:
  sphinx:
    name: Sphinx
    runs-on: ubuntu-latest
    env:
      VENVPATH: /usr 
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: make env-doc
    - name: Sphinx Doctest
      working-directory: sphinx
      run: make doctest
    - name: Sphinx Build
      working-directory: sphinx
      run: 
        make html
        touch _build/html/.nojekyll 
    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        BRANCH: gh-pages
        FOLDER: sphinx/_build/html
        CLEAN: true
